import { PatientData } from './types';

export const medicalTerms: Record<string, string> = {
  'hemoglobine': 'Een eiwit in rode bloedcellen dat zuurstof door uw lichaam vervoert. Een te lage waarde kan duiden op bloedarmoede.',
  'glucose': 'Bloedsuiker. Dit is de belangrijkste brandstof voor uw lichaam. Een te hoge waarde kan wijzen op diabetes.',
  'cholesterol': 'Een vetachtige stof in uw bloed. Uw lichaam heeft het nodig, maar te veel verhoogt het risico op hart- en vaatziekten.',
  'hdl': 'De "goede" cholesterol. HDL ruimt overtollig cholesterol op uit uw bloedvaten en beschermt zo tegen hart- en vaatziekten.',
  'ldl': 'De "slechte" cholesterol. LDL kan zich ophopen in uw bloedvaten en deze vernauwen, wat het risico op een hartaanval verhoogt.',
  'triglyceriden': 'Vetten in uw bloed die uw lichaam als energie gebruikt. Te hoge waarden verhogen het risico op hart- en vaatziekten.',
  'tsh': 'Schildklierstimulerend hormoon. Dit hormoon stuurt de schildklier aan. Een te hoge waarde kan betekenen dat uw schildklier te traag werkt.',
  'vrij t4': 'Een schildklierhormoon dat uw stofwisseling regelt. Een te lage waarde kan duiden op een te traag werkende schildklier.',
  'anti-tpo': 'Antistoffen tegen schildklierweefsel. Hoge waarden wijzen op een auto-immuunreactie waarbij het lichaam de eigen schildklier aanvalt.',
  'hba1c': 'Langetermijn bloedsuiker. Laat zien hoe hoog uw bloedsuiker gemiddeld was over de afgelopen 2-3 maanden.',
  'kreatinine': 'Een afvalstof van uw spieren die door de nieren wordt gefilterd. Een hoge waarde kan betekenen dat uw nieren minder goed werken.',
  'egfr': 'Geschatte nierfunctie. Geeft aan hoe goed uw nieren het bloed filteren. Een lagere waarde betekent verminderde nierfunctie.',
  'kalium': 'Een mineraal dat belangrijk is voor uw hartritme en spierfunctie. Te hoog of te laag kan gevaarlijk zijn.',
  'albumine': 'Een eiwit in uw bloed dat belangrijk is voor uw voedingstoestand en vochtbalans in het lichaam.',
  'calcium': 'Een mineraal dat nodig is voor sterke botten, spierfunctie en zenuwwerking.',
  'fosfaat': 'Een mineraal dat samenwerkt met calcium voor sterke botten. Bij nierproblemen kan de fosfaatwaarde stijgen.',
  'erytropoetine': 'Een hormoon dat door de nieren wordt gemaakt en de aanmaak van rode bloedcellen stimuleert.',
  'bloeddruk': 'De druk waarmee het bloed door uw slagaders stroomt. Te hoge bloeddruk belast het hart en de bloedvaten.',
  'vitamine d': 'Een vitamine die belangrijk is voor sterke botten en uw afweersysteem. Wordt aangemaakt door zonlicht op de huid.',
  'ferritine': 'Een eiwit dat ijzer opslaat in uw lichaam. Een lage waarde wijst op een laag ijzergehalte.',
  'leukocyten': 'Witte bloedcellen. Onderdeel van uw afweersysteem dat infecties bestrijdt.',
  'trombocyten': 'Bloedplaatjes. Zorgen ervoor dat uw bloed kan stollen bij een wond.',
  'hypothyreodie': 'Een te traag werkende schildklier. Hierdoor maakt uw lichaam te weinig schildklierhormonen.',
  'bloedsuiker': 'De hoeveelheid suiker (glucose) in uw bloed. Uw lichaam gebruikt dit als brandstof.',
  'diabetes': 'Een aandoening waarbij uw lichaam moeite heeft om de bloedsuiker te reguleren.',
  'nierfunctie': 'Hoe goed uw nieren werken bij het filteren van afvalstoffen uit het bloed.',
  'schildklier': 'Een klier in uw hals die hormonen maakt voor uw stofwisseling, energieniveau en lichaamstemperatuur.',
  'bloedarmoede': 'Een tekort aan rode bloedcellen of hemoglobine, waardoor uw lichaam minder zuurstof kan vervoeren.',
  'stofwisseling': 'Alle processen in uw lichaam die voedsel omzetten in energie en bouwstoffen.',
  'rode bloedcellen': 'Cellen in uw bloed die zuurstof vervoeren van de longen naar de rest van uw lichaam.',
  'afweersysteem': 'Het verdedigingssysteem van uw lichaam dat infecties en ziekten bestrijdt.',
};

export const patientData: Record<string, PatientData> = {
  routine: {
    name: 'Maria van den Berg', age: 52,
    context: 'Jaarlijkse bloedcontrole via huisarts',
    date: '23 januari 2025',
    lab: [
      { test: 'Hemoglobine (Hb)', value: '8.2', unit: 'mmol/L', ref: '7.5 - 10.0', status: 'normal' },
      { test: 'Glucose (nuchter)', value: '5.4', unit: 'mmol/L', ref: '3.1 - 6.4', status: 'normal' },
      { test: 'Cholesterol (totaal)', value: '6.8', unit: 'mmol/L', ref: '< 5.0', status: 'high' },
      { test: 'HDL-cholesterol', value: '1.8', unit: 'mmol/L', ref: '> 1.2', status: 'normal' },
      { test: 'LDL-cholesterol', value: '4.2', unit: 'mmol/L', ref: '< 3.0', status: 'high' },
      { test: 'Triglyceriden', value: '1.7', unit: 'mmol/L', ref: '< 2.0', status: 'normal' },
      { test: 'TSH', value: '2.1', unit: 'mU/L', ref: '0.4 - 4.0', status: 'normal' },
      { test: 'Kreatinine', value: '72', unit: 'umol/L', ref: '45 - 90', status: 'normal' },
    ],
    ai: {
      greeting: 'Beste Maria, hier zijn uw uitslagen van 23 januari uitgelegd.',
      results: [
        { type: 'good', title: 'Bloedbeeld en suiker: prima in orde', value: 'Hemoglobine 8.2 mmol/L | Glucose 5.4 mmol/L', explain: 'Uw bloedwaarden zijn goed. De hemoglobine laat zien dat uw bloed genoeg rode bloedcellen heeft om zuurstof te vervoeren. Uw bloedsuiker is normaal, wat betekent dat uw lichaam suiker goed verwerkt.' },
        { type: 'attention', title: 'Cholesterol: iets te hoog', value: 'Totaal cholesterol 6.8 mmol/L (streefwaarde: onder 5.0) | LDL 4.2 mmol/L (streefwaarde: onder 3.0)', explain: 'Uw cholesterol is verhoogd. Er zijn twee soorten: HDL ("goede" cholesterol) en LDL ("slechte" cholesterol). Uw HDL is goed, maar uw LDL is te hoog. Te veel LDL kan zich ophopen in uw bloedvaten, waardoor het risico op hart- en vaatziekten toeneemt. Dit is niet acuut gevaarlijk, maar wel iets om aan te werken.' },
        { type: 'good', title: 'Schildklier en nieren: normaal', value: 'TSH 2.1 mU/L | Kreatinine 72 umol/L', explain: 'Uw schildklier werkt goed en uw nieren filteren uw bloed prima. Hier is geen actie voor nodig.' },
      ],
      summary: 'De meeste uitslagen zijn goed. Het enige aandachtspunt is uw cholesterol. Dit is iets dat u samen met uw huisarts kunt bespreken. Vaak helpen kleine aanpassingen in voeding en beweging al.',
      actions: [
        'Bespreek het cholesterol met uw huisarts bij de volgende afspraak',
        'Voedingsadvies: minder verzadigd vet (boter, kaas, vettig vlees), meer vis, noten en groente',
        'Regelmatig bewegen helpt om LDL te verlagen — al 30 minuten wandelen per dag maakt verschil',
      ],
    },
    chatQA: [
      { keywords: ['cholesterol', 'te hoog', 'verhoogd', 'gevaarlijk'], question: 'Is mijn cholesterol gevaarlijk?', answer: 'Uw totaal cholesterol is 6.8 mmol/L, dat is boven de streefwaarde van 5.0. Uw LDL (de "slechte" cholesterol) is 4.2, terwijl onder 3.0 gewenst is. Dit is niet acuut gevaarlijk, maar op de lange termijn verhoogt het uw risico op hart- en vaatziekten. Het goede nieuws: uw HDL (de "goede" cholesterol) is prima, en met aanpassingen in voeding en beweging kunt u het LDL vaak verlagen. Uw huisarts kan dit met u bespreken.' },
      { keywords: ['wat kan ik doen', 'verlagen', 'voeding', 'dieet', 'eten'], question: 'Wat kan ik doen om mijn cholesterol te verlagen?', answer: 'Er zijn bewezen effectieve aanpassingen: verminder verzadigd vet (boter, kaas, vettig vlees, koek), eet meer onverzadigde vetten (olijfolie, noten, vette vis), eet meer vezels (groente, fruit, volkoren producten), en beweeg minimaal 30 minuten per dag. Bij sommige patiënten is een cholesterolverlager (statine) nodig. Uw huisarts beoordeelt dit op basis van uw totale risicoprofiel.' },
      { keywords: ['medicijn', 'statine', 'pil', 'medicatie'], question: 'Heb ik medicijnen nodig?', answer: 'Dat hangt af van uw totale risicoprofiel. Uw huisarts kijkt niet alleen naar het cholesterol, maar ook naar andere factoren zoals leeftijd, bloeddruk, roken en familiegeschiedenis. Bij een licht verhoogd cholesterol zonder andere risicofactoren is leefstijlaanpassing vaak voldoende. Als dat niet genoeg helpt, kan uw arts een statine voorschrijven.' },
    ],
  },
  diabetes: {
    name: 'Ahmed Yilmaz', age: 64,
    context: '3-maandelijkse diabetes type 2 controle',
    date: '20 januari 2025',
    lab: [
      { test: 'HbA1c', value: '58', unit: 'mmol/mol', ref: '< 53', status: 'high' },
      { test: 'Glucose (nuchter)', value: '8.9', unit: 'mmol/L', ref: '4.0 - 7.0', status: 'high' },
      { test: 'Kreatinine', value: '98', unit: 'umol/L', ref: '60 - 110', status: 'normal' },
      { test: 'eGFR', value: '68', unit: 'mL/min', ref: '> 60', status: 'normal' },
      { test: 'Albumine/kreatinine ratio', value: '4.2', unit: 'mg/mmol', ref: '< 3.5', status: 'high' },
      { test: 'Cholesterol (totaal)', value: '4.8', unit: 'mmol/L', ref: '< 5.0', status: 'normal' },
      { test: 'Kalium', value: '4.6', unit: 'mmol/L', ref: '3.5 - 5.0', status: 'normal' },
      { test: 'Bloeddruk', value: '148/92', unit: 'mmHg', ref: '< 140/80', status: 'high' },
    ],
    ai: {
      greeting: 'Beste meneer Yilmaz, hier zijn de uitslagen van uw diabetescontrole van 20 januari.',
      results: [
        { type: 'attention', title: 'Langetermijn bloedsuiker (HbA1c): iets te hoog', value: 'HbA1c: 58 mmol/mol (streefwaarde: onder 53)', explain: 'Het HbA1c laat zien hoe hoog uw bloedsuiker gemiddeld was over de afgelopen 3 maanden. Uw waarde van 58 is iets boven de streefwaarde. Dit betekent dat uw diabetes op dit moment niet optimaal gereguleerd is.' },
        { type: 'attention', title: 'Eiwit in urine: licht verhoogd', value: 'Albumine/kreatinine ratio: 4.2 mg/mmol (streefwaarde: onder 3.5)', explain: 'Er zit een klein beetje eiwit in uw urine. Bij diabetes kan dit lekken. Dit is een vroeg signaal dat uw nieren iets harder moeten werken.' },
        { type: 'attention', title: 'Bloeddruk: te hoog', value: '148/92 mmHg (streefwaarde: onder 140/80)', explain: 'Uw bloeddruk is te hoog. Bij diabetes is een goede bloeddruk extra belangrijk, omdat hoge bloeddruk samen met hoge bloedsuiker de kans op nierschade vergroot.' },
        { type: 'good', title: 'Cholesterol en kalium: goed', value: 'Cholesterol 4.8 mmol/L | Kalium 4.6 mmol/L', explain: 'Uw cholesterol is netjes binnen de norm en uw kalium is goed. De cholesterolverlager die u gebruikt doet zijn werk.' },
      ],
      summary: 'Er zijn drie punten om met uw arts te bespreken: uw bloedsuiker is iets te hoog, er zit een klein beetje eiwit in uw urine, en uw bloeddruk is verhoogd. Het goede nieuws: het is allemaal licht verhoogd en goed behandelbaar.',
      actions: [
        'Maak een afspraak met uw diabetesverpleegkundige om uw medicatie te bespreken',
        'Het HbA1c kan dalen door regelmatig eten op vaste tijden en minder snelle suikers',
        'Bloeddruk verlagen: minder zout, dagelijks bewegen, en eventueel medicatie-aanpassing',
      ],
    },
    chatQA: [
      { keywords: ['hba1c', 'bloedsuiker', 'te hoog', 'suiker', '58'], question: 'Wat betekent een HbA1c van 58?', answer: 'Uw HbA1c van 58 mmol/mol betekent dat uw gemiddelde bloedsuiker over de afgelopen 3 maanden iets te hoog is geweest. De streefwaarde bij diabetes type 2 is onder de 53. Een verschil van 5 punten is niet alarmerend, maar het is wel een signaal om met uw diabetesverpleegkundige te kijken naar uw medicatie en voeding.' },
      { keywords: ['eiwit', 'urine', 'nieren', 'albumine', 'nierschade'], question: 'Is het eiwit in mijn urine een probleem?', answer: 'Er zit een klein beetje eiwit in uw urine (albumine/kreatinine ratio 4.2, normaal onder 3.5). Dit is een vroeg waarschuwingssignaal. Uw nierfunctie zelf (eGFR 68) is nog redelijk. Door uw bloedsuiker en bloeddruk goed te reguleren, kunt u verdere achteruitgang voorkomen.' },
      { keywords: ['bloeddruk', 'hoog', 'verlagen'], question: 'Hoe kan ik mijn bloeddruk verlagen?', answer: 'Uw bloeddruk van 148/92 is te hoog. Wat u kunt doen: minder zout eten (max 6 gram per dag), dagelijks 30 minuten bewegen, eventueel afvallen, en alcohol matigen. Als leefstijlaanpassingen niet voldoende helpen, kan uw arts bloeddrukmedicatie voorschrijven of aanpassen.' },
    ],
  },
  nier: {
    name: 'Jan de Vries', age: 71,
    context: 'Controle na eerder vastgestelde nierfunctievermindering',
    date: '18 januari 2025',
    lab: [
      { test: 'Kreatinine', value: '156', unit: 'umol/L', ref: '60 - 110', status: 'high' },
      { test: 'eGFR', value: '38', unit: 'mL/min', ref: '> 60', status: 'low' },
      { test: 'Ureum', value: '12.8', unit: 'mmol/L', ref: '2.5 - 7.5', status: 'high' },
      { test: 'Kalium', value: '5.4', unit: 'mmol/L', ref: '3.5 - 5.0', status: 'high' },
      { test: 'Fosfaat', value: '1.62', unit: 'mmol/L', ref: '0.8 - 1.5', status: 'high' },
      { test: 'Hemoglobine (Hb)', value: '6.8', unit: 'mmol/L', ref: '8.5 - 11.0', status: 'low' },
      { test: 'Calcium', value: '2.18', unit: 'mmol/L', ref: '2.20 - 2.60', status: 'low' },
      { test: 'Albumine', value: '32', unit: 'g/L', ref: '35 - 50', status: 'low' },
    ],
    ai: {
      greeting: 'Beste meneer De Vries, hier zijn uw uitslagen van de niercontrole van 18 januari.',
      results: [
        { type: 'alert', title: 'Nierfunctie: duidelijk verminderd', value: 'eGFR: 38 mL/min (normaal: boven 60) | Kreatinine: 156 umol/L', explain: 'Uw nieren werken op ongeveer 38% van hun normale capaciteit. De hoge kreatinine en ureum laten zien dat er meer afvalstoffen in uw bloed achterblijven dan normaal. Dit past bij stadium 3b van chronische nierschade.' },
        { type: 'alert', title: 'Kalium: verhoogd — belangrijk', value: 'Kalium: 5.4 mmol/L (normaal: 3.5 - 5.0)', explain: 'Uw kalium is iets te hoog. Kalium is een mineraal dat belangrijk is voor uw hartritme. Een kalium boven 5.5 kan gevaarlijk zijn voor uw hart. U zit daar net onder, maar dit moet goed in de gaten gehouden worden.' },
        { type: 'attention', title: 'Bloedarmoede en mineralen verstoord', value: 'Hemoglobine: 6.8 mmol/L | Calcium: 2.18 | Fosfaat: 1.62', explain: 'U heeft bloedarmoede: uw hemoglobine is te laag. Bij verminderde nierfunctie maken de nieren minder erytropoetine aan. Ook zijn uw calcium en fosfaat uit balans, wat op den duur uw botten kan verzwakken.' },
        { type: 'attention', title: 'Albumine: te laag', value: 'Albumine: 32 g/L (normaal: 35-50)', explain: 'Albumine is een eiwit in uw bloed dat belangrijk is voor uw voedingstoestand. Een lage waarde kan betekenen dat u te weinig eiwitten binnenkrijgt.' },
      ],
      summary: 'Uw nierfunctie is verminderd (stadium 3b) en dit veroorzaakt een keten van effecten: ophoping van afvalstoffen, verstoorde mineralen, en bloedarmoede. De uitslagen van vandaag moeten met uw specialist besproken worden, vooral het kalium dat aan de hoge kant zit.',
      actions: [
        'Bel de nefroloog of het secretariaat om de uitslagen te bespreken (vooral het kalium)',
        'Vermijd kaliumrijke voeding totdat u uw arts heeft gesproken (bananen, tomaten, aardappelen)',
        'Neem uw medicijnen in zoals voorgeschreven — sla geen dosis over',
      ],
    },
    chatQA: [
      { keywords: ['kalium', 'gevaarlijk', 'hart', 'hoog', '5.4'], question: 'Is mijn kalium gevaarlijk hoog?', answer: 'Uw kalium is 5.4 mmol/L, net boven de bovengrens van 5.0. Boven 5.5 kan kalium gevaarlijk worden voor uw hartritme. Eet voorzichtig met kaliumrijke voeding zoals bananen, tomaten, aardappelen en chocolade. Neem zo snel mogelijk contact op met uw nefroloog.' },
      { keywords: ['nierfunctie', 'egfr', '38', 'stadium', 'achteruit'], question: 'Gaat mijn nierfunctie nog verder achteruit?', answer: 'Uw eGFR is 38 mL/min, wat past bij stadium 3b chronische nierschade. Door uw bloeddruk goed te reguleren, zoutarm te eten en uw medicijnen trouw in te nemen, kunt u de achteruitgang vaak vertragen.' },
      { keywords: ['bloedarmoede', 'moe', 'hemoglobine', 'vermoeid'], question: 'Waarom heb ik bloedarmoede?', answer: 'Uw hemoglobine is 6.8 mmol/L, onder de norm. Bij verminderde nierfunctie maken uw nieren minder erytropoetine (EPO) aan. Dit hormoon stimuleert de aanmaak van rode bloedcellen. Uw nefroloog kan een EPO-injectie of ijzersupplement voorschrijven.' },
    ],
  },
  schildklier: {
    name: 'Lisa Bakker', age: 38,
    context: 'Onderzoek naar oorzaak van vermoeidheid en gewichtstoename',
    date: '22 januari 2025',
    lab: [
      { test: 'TSH', value: '8.7', unit: 'mU/L', ref: '0.4 - 4.0', status: 'high' },
      { test: 'Vrij T4 (fT4)', value: '9.2', unit: 'pmol/L', ref: '11.0 - 22.0', status: 'low' },
      { test: 'Anti-TPO', value: '312', unit: 'kU/L', ref: '< 35', status: 'high' },
      { test: 'Hemoglobine (Hb)', value: '7.4', unit: 'mmol/L', ref: '7.5 - 10.0', status: 'low' },
      { test: 'Ferritine', value: '12', unit: 'ug/L', ref: '20 - 200', status: 'low' },
      { test: 'Vitamine D', value: '28', unit: 'nmol/L', ref: '50 - 125', status: 'low' },
      { test: 'Glucose (nuchter)', value: '4.8', unit: 'mmol/L', ref: '3.1 - 6.4', status: 'normal' },
      { test: 'Cholesterol (totaal)', value: '5.9', unit: 'mmol/L', ref: '< 5.0', status: 'high' },
    ],
    ai: {
      greeting: 'Beste Lisa, hier zijn uw uitslagen van 22 januari. Er is een duidelijke verklaring gevonden voor uw klachten.',
      results: [
        { type: 'alert', title: 'Schildklier: te traag (hypothyreodie)', value: 'TSH: 8.7 mU/L | Vrij T4: 9.2 pmol/L | Anti-TPO: 312 kU/L', explain: 'Uw schildklier werkt te langzaam. Het schildklierhormoon (T4) is te laag en het aansturingshormoon (TSH) te hoog. De hoge Anti-TPO waarde laat zien dat uw afweersysteem de schildklier aanvalt — dit heet de ziekte van Hashimoto. Dit verklaart uw vermoeidheid en gewichtstoename.' },
        { type: 'attention', title: 'IJzertekort en lichte bloedarmoede', value: 'Ferritine: 12 ug/L | Hemoglobine: 7.4 mmol/L', explain: 'Uw ijzervoorraad is te laag en uw hemoglobine zit net onder de grens. Een tekort geeft extra vermoeidheid bovenop de schildklierklachten.' },
        { type: 'attention', title: 'Vitamine D: te laag', value: 'Vitamine D: 28 nmol/L (normaal: 50-125)', explain: 'Uw vitamine D is flink te laag. Een tekort kan ook bijdragen aan vermoeidheid en somberheid. In Nederland is dit in de winter heel gebruikelijk.' },
        { type: 'info', title: 'Cholesterol: iets verhoogd (past bij schildklier)', value: 'Cholesterol: 5.9 mmol/L', explain: 'Uw cholesterol is licht verhoogd. Dit past bij een trage schildklier: als de stofwisseling trager is, wordt cholesterol minder snel afgebroken. Zodra uw schildklier wordt behandeld, zal het cholesterol waarschijnlijk vanzelf dalen.' },
      ],
      summary: 'Er is goed nieuws: er is een duidelijke verklaring voor uw klachten gevonden. U heeft de ziekte van Hashimoto, een ijzertekort en een vitamine D-tekort. Alle drie zijn goed behandelbaar.',
      actions: [
        'Uw huisarts zal schildkliermedicatie voorschrijven (levothyroxine) — elke ochtend op een lege maag',
        'Start met een ijzersupplement — uw arts kan dit voorschrijven of adviseren',
        'Start met vitamine D-supplement (1000-2000 IE per dag in de winter)',
        'Na 6-8 weken wordt uw bloed opnieuw gecontroleerd',
      ],
    },
    chatQA: [
      { keywords: ['hashimoto', 'schildklier', 'auto-immuun', 'wat is'], question: 'Wat is de ziekte van Hashimoto?', answer: 'De ziekte van Hashimoto is een auto-immuunziekte waarbij uw eigen afweersysteem de schildklier aanvalt. Uw hoge Anti-TPO waarde (312, normaal onder 35) bevestigt deze diagnose. Het is de meest voorkomende oorzaak van een trage schildklier en komt vaker voor bij vrouwen. Het is goed behandelbaar met schildklierhormoon in tabletvorm (levothyroxine).' },
      { keywords: ['levothyroxine', 'medicijn', 'bijwerking', 'hoelang', 'innemen'], question: 'Hoe werkt levothyroxine?', answer: 'Levothyroxine is een synthetische vorm van het schildklierhormoon T4. U neemt het als tablet elke ochtend op een lege maag in, minstens 30 minuten voor het ontbijt. De dosering wordt geleidelijk ingesteld op basis van bloedcontroles. Bij de ziekte van Hashimoto is de behandeling doorgaans levenslang.' },
      { keywords: ['ijzer', 'ferritine', 'supplement', 'ijzertekort'], question: 'Hoe kan ik mijn ijzertekort aanpakken?', answer: 'Uw ferritine is 12 ug/L (normaal: 20-200). Uw arts kan een ijzertablet voorschrijven. Neem dit in op een lege maag met sinaasappelsap (vitamine C bevordert opname). Vermijd gelijktijdige inname met koffie, thee of zuivel. Na 3 maanden wordt uw bloed opnieuw gecontroleerd.' },
    ],
  },
};
